apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: podinfo
  namespace: monitoring
  labels:
    app.kubernetes.io/name: podinfo
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo
  namespaceSelector:
    matchNames:
      - podinfo
  endpoints:
    - port: http
      path: /metrics
      interval: 15s