apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: homelab
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  source:
    repoURL: https://gitea.webdemoapp.com/homelab-devops/homelab-gitops
    targetRevision: main
    path: gateway-migration/kyverno/kyverno-policies
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      jsonPointers:
        - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions: []