apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo-rollout
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: homelab
spec:
  project: homelab
  source:
    repoURL: https://gitea.webdemoapp.com/homelab-devops/homelab-gitops.git
    targetRevision: HEAD
    path: gateway-migration/podinfo
    directory:
      recurse: false
      include: '{rollout.yaml,services.yaml,httproute.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: podinfo
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: true
      selfHeal: true
